### ISSUE TITLE
when i navigate to url, err orrcus : "errorOnGetInfo"

### ISSUE THREAD

**Issue by anhtrung0000** [Wpdas/horizon-youtube-mp3#1]
$ node index.js
Server running!
Put on browser: http://localhost:3000/?youtubeURL=http://youtube.com/watch?v=NEA0BLnpOtg
URL Video: http://youtube.com/watch?v=NEA0BLnpOtg
errorOnGetInfo.
URL Video: http://youtube.com/watch?v=NEA0BLnpOtg
errorOnGetInfo.
what did i miss? and how to fix that err. Thanks.
p/s: my English not good. hope u help.

**Comment by mrinc** [comment]
@anhtrung0000 - Use the YTDL-CORE library they are referencing here directly: https://github.com/fent/node-ytdl-core

Worked for me when I got the same issue - could be related to updates from youtube, so just updating the module in this project could help.

**Comment by wpdas** [comment]
I did the adjustment to fix this problem. Thank you @mrinc . Please update the lib.
