### ISSUE TITLE
TLS-Cert for youtubetransfer.com. expired on 2019-01-07

### ISSUE THREAD

**Issue by fdenzer** [Wpdas/horizon-youtube-mp3#5]
The letsencrypt certificate for https://youtubetransfer.com/ does not seem to update: at the time of writing, it expired 41 days ago.

**Comment by wpdas** [comment]
Hey buddy, I've finished my account on Godaddy due to issues using their server. However, the package is still working. There are some limitations in YouTube side unfortunately.
